"""Alembic environment for NetVision SQLite database.

SQLite is configured with PRAGMAs (WAL, foreign_keys) at the connection
level by db_manager.py. Since we use raw sqlite3 (no SQLAlchemy ORM),
migrations are written as raw SQL rather than autogenerated.
"""

from logging.config import fileConfig

from sqlalchemy import engine_from_config
from sqlalchemy import pool

from alembic import context

# Alembic Config object
config = context.config

# Logging setup
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# No SQLAlchemy ORM models — migrations are hand-written raw SQL
target_metadata = None


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode.

    SQL is emitted to stdout (or saved to file) without connecting
    to the DB. Use with: alembic upgrade --sql
    """
    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        # SQLite doesn't support ALTER RENAME COLUMN or DROP COLUMN natively;
        # Alembic can use batch mode to work around this.
        render_as_batch=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode against a live SQLite database."""
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        # Enable WAL + foreign_keys for the migration connection
        connection.exec_driver_sql("PRAGMA journal_mode=WAL")
        connection.exec_driver_sql("PRAGMA foreign_keys=OFF")  # OFF during migration

        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            render_as_batch=True,
        )

        with context.begin_transaction():
            context.run_migrations()

        # Re-enable foreign_keys after migration
        connection.exec_driver_sql("PRAGMA foreign_keys=ON")


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
